### ISSUE TITLE
What‘s the paper of Dense LSTM?

### ISSUE THREAD

**Issue by KaiJin1995** [ahmedius2/Human-Action-Recognition-using-Dense-LSTM#2]
I want to know what paper do you refer to ? Is the architecture designed by yourself?

**Comment by ahmedius2** [comment]
The idea belongs to @SeymaYucer , she was thinking that the DenseNet idea can also be applied to multi layered LSTM's. While I was imlementing it for human regocnition problem, we saw a paper that somebody else implemented and publised it for NLP.

**Comment by KaiJin1995** [comment]
I get it. Thanks!
